name: Publish
on:
  push:
    tags:
      - '*'


jobs:
  TERUpload:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v1
      - uses: tomasnorre/typo3-upload-ter@v2
        with:
          api-token: ${{ secrets.TYPO3_API_TOKEN }}

jobs:
  publish:
    name: Publish to TER
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Set up PHP Version 7.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
      - name: Publish to TER
        uses: the-coding-owl/action-typo3-extension-repository-upload@0.0.1
        env:
          SECRET_USERNAME: ${{ secrets.USERNAME }}
          SECRET_PASSWORD: ${{ secrets.PASSWORD }}
          EXTENSION_KEY: 'logformatter'
          UPLOAD_MESSAGE: ${{ github.event.head_commit.message }}
